DEV | Employee Qualification Service Unit Test
RetroRabbit/RGO-Server pull request #107
Opened 2024-05-17 12:38 UTC by bseptember

### **Overview:**

This pull request adds comprehensive unit tests for the EmployeeQualificationService class, enhancing the overall test coverage and ensuring the robustness of the service methods.

### **Changes Made:**

Added EmployeeQualificationServiceUnitTests.cs

### **Setup Methods:**

- SetupEmployeeExists(): Configures mock behavior for an existing employee.

- SetupEmployeeDoesNotExist(): Configures mock behavior for a non-existent employee.

- SetupLogException(): Configures mock behavior for logging exceptions.

### **Verification Methods:**

- VerifyLogExceptionCalled(Times times): Verifies the number of times the exception logging was called.

- VerifyGetEmployeeByIdCalled(Times times): Verifies the number of times GetEmployeeById was called.

- VerifyAddQualificationCalled(Times times): Verifies the number of times a qualification was added.

- VerifyDeleteQualificationCalled(Times times): Verifies the number of times a qualification was deleted.

### **Unit Tests:**

- SaveEmployeeQualification_Success_WithValidData_ReturnsQualificationsList(): Tests successful saving of qualifications.

- SaveEmployeeQualification_Failure_WithNonExistingEmployee_ThrowsException(): Tests failure case when saving qualifications for a non-existent employee.

- GetAllEmployeeQualifications_Success_WithValidData_ReturnsQualificationsList(): Tests successful retrieval of all qualifications.

- GetAllEmployeeQualifications_Failure_WhenRetrievalFails_ThrowsException(): Tests failure case for retrieving qualifications.

- GetAllEmployeeQualificationsByEmployeeId_Success_WithValidEmployeeId_ReturnsQualifications(): Tests successful retrieval of qualifications by employee ID.

- GetAllEmployeeQualificationsByEmployeeId_Failure_WithInvalidEmployeeId_ThrowsInvalidOperationException(): Tests failure case for invalid employee ID.

- GetAllEmployeeQualificationsByEmployeeId_Failure_WithNonExistingEmployee_ThrowsKeyNotFoundException(): Tests failure case for non-existent employee ID.

- GetAllEmployeeQualificationsByEmployeeId_Failure_ExceptionThrown_LogsAndRethrows(): Tests logging and rethrowing of exceptions.

- GetEmployeeQualificationById_Success_WithExistingId_ReturnsQualification(): Tests successful retrieval of a qualification by ID.

- GetEmployeeQualificationById_Failure_WithNonExistingId_ThrowsException(): Tests failure case for non-existent qualification ID.

- GetEmployeeQualificationById_FailureWithNonExistingId_ThrowsNullException(): Tests null exception case.

- UpdateEmployeeQualification_Success(): Tests successful updating of a qualification.

- UpdateEmployeeQualification_Failure(): Tests failure case for updating a non-existent qualification.

- DeleteEmployeeQualification_Success(): Tests successful deletion of a qualification.

- DeleteEmployeeQualification_Failure_WhenDeletionFails_ThrowsException(): Tests failure case for qualification deletion.

### **Testing:**

- The new unit tests were executed to ensure they pass and provide accurate coverage for the EmployeeQualificationService methods.

- Verified that the service handles both success and failure scenarios correctly, logging exceptions where appropriate.

![image](https://github.com/RetroRabbit/RGO-Server/assets/68727050/cee4e1b2-0ea3-4813-bc7f-a38fdc1e44ed)

2024-05-17 12:56 UTC, dvanhout89 requested changes

2024-05-17 12:56 UTC, dvanhout89 commented on HRIS.Services.Tests/Services/EmployeeQualificationServiceUnitTests.cs
> +        // Shared test data
```suggestion
```

2024-05-17 12:56 UTC, dvanhout89 commented on HRIS.Services.Tests/Services/EmployeeQualificationServiceUnitTests.cs
> +            // Initialize shared test mock data
```suggestion
```

2024-05-17 12:56 UTC, dvanhout89 commented on HRIS.Services.Tests/Services/EmployeeQualificationServiceUnitTests.cs
> +            // Verify that the error logging service was not called during a successful operation
```suggestion
```

2024-05-17 12:56 UTC, dvanhout89 commented on HRIS.Services.Tests/Services/EmployeeQualificationServiceUnitTests.cs
> +            // Verify that the unitOfWork's EmployeeQualification.Add method was called with the correct parameter
```suggestion
```

2024-05-17 12:56 UTC, dvanhout89 commented on HRIS.Services.Tests/Services/EmployeeQualificationServiceUnitTests.cs
> +            // Verify that the employee service's GetEmployeeById method was called with the correct employeeId
```suggestion
```

2024-05-17 12:56 UTC, dvanhout89 commented on HRIS.Services.Tests/Services/EmployeeQualificationServiceUnitTests.cs
> +            // Verify that the Delete method of the repository was called with the correct ID
```suggestion
```

2024-05-17 12:56 UTC, dvanhout89 commented on HRIS.Services.Tests/Services/EmployeeQualificationServiceUnitTests.cs
> +            // Verify that the result is not null
```suggestion
```

2024-05-17 12:56 UTC, dvanhout89 commented on HRIS.Services.Tests/Services/EmployeeQualificationServiceUnitTests.cs
> +            // Act
```suggestion
```

2024-05-17 12:56 UTC, dvanhout89 commented on HRIS.Services.Tests/Services/EmployeeQualificationServiceUnitTests.cs
> +            // Setup mock
```suggestion
```

2024-05-17 12:56 UTC, dvanhout89 commented on HRIS.Services.Tests/Services/EmployeeQualificationServiceUnitTests.cs
> +            // Setup mocks
```suggestion
```

2024-05-17 12:56 UTC, dvanhout89 commented on HRIS.Services.Tests/Services/EmployeeQualificationServiceUnitTests.cs
> +            // Execute the method under test and capture the thrown exception
```suggestion
```

2024-05-17 12:56 UTC, dvanhout89 commented on HRIS.Services.Tests/Services/EmployeeQualificationServiceUnitTests.cs
> +            // Setup mock
```suggestion
```

2024-05-17 12:56 UTC, dvanhout89 commented on HRIS.Services.Tests/Services/EmployeeQualificationServiceUnitTests.cs
> +            // Act
```suggestion
```

2024-05-17 12:56 UTC, dvanhout89 commented on HRIS.Services.Tests/Services/EmployeeQualificationServiceUnitTests.cs
> +            // Arrange
```suggestion
```

2024-05-17 12:56 UTC, dvanhout89 commented on HRIS.Services.Tests/Services/EmployeeQualificationServiceUnitTests.cs
> +            var deletedQualificationDto = new EmployeeQualificationDto { Id = _qualificationId }; // Mock the deleted qualification DTO
```suggestion
            var deletedQualificationDto = new EmployeeQualificationDto { Id = _qualificationId };
```

2024-05-17 12:56 UTC, dvanhout89 commented on HRIS.Services.Tests/Services/EmployeeQualificationServiceUnitTests.cs
> +            Assert.Equal(_qualificationId, result.Id); // Verify that the returned DTO has the expected ID
```suggestion
            Assert.Equal(_qualificationId, result.Id);
```

2024-05-17 12:56 UTC, dvanhout89 commented on HRIS.Services.Tests/Services/EmployeeQualificationServiceUnitTests.cs
> +            // Setup mock
```suggestion
```

2024-05-17 12:56 UTC, dvanhout89 commented on HRIS.Services.Tests/Services/EmployeeQualificationServiceUnitTests.cs
> +                .ThrowsAsync(new Exception("Delete operation failed")); // Simulate a failure scenario where an exception occurs during deletion
```suggestion
                .ThrowsAsync(new Exception("Delete operation failed"));
```

2024-05-17 12:56 UTC, dvanhout89 commented on HRIS.Services.Tests/Services/EmployeeQualificationServiceUnitTests.cs
> +            // Act & Assert
```suggestion
```

2024-05-17 12:56 UTC, dvanhout89 commented on HRIS.Services.Tests/Services/EmployeeQualificationServiceUnitTests.cs
> +            // Assert
```suggestion
```

2024-05-17 12:56 UTC, dvanhout89 commented on HRIS.Services.Tests/Services/EmployeeQualificationServiceUnitTests.cs
> +            Assert.Equal("Delete operation failed", exception.Message); // Verify the correct exception message
```suggestion
            Assert.Equal("Delete operation failed", exception.Message);
```

2024-05-17 12:56 UTC, dvanhout89 commented on HRIS.Services.Tests/Services/EmployeeQualificationServiceUnitTests.cs
> +               .Returns(mockQualifications); // Returning the mocked IQueryable
```suggestion
               .Returns(mockQualifications);
```

2024-05-17 12:56 UTC, dvanhout89 commented on HRIS.Services.Tests/Services/EmployeeQualificationServiceUnitTests.cs
> +            Assert.Single(result); // Since there's only one qualification in the list
```suggestion
            Assert.Single(result);
```

2024-05-17 12:56 UTC, dvanhout89 commented on HRIS.Services.Tests/Services/EmployeeQualificationServiceUnitTests.cs
> +            // Verify that the returned result matches the expected employee qualification DTO
```suggestion
```

2024-05-17 12:56 UTC, dvanhout89 commented on HRIS.Services.Tests/Services/EmployeeQualificationServiceUnitTests.cs
> +            // Setup mock to return null, simulating the scenario where employee does not exist
```suggestion
```
```suggestion
```

2024-05-17 12:56 UTC, dvanhout89 commented on HRIS.Services.Tests/Services/EmployeeQualificationServiceUnitTests.cs
> +            // Setup mock for getting employee by ID
```suggestion
```

2024-05-17 13:17 UTC, dvanhout89 approved these changes
👍

2024-05-20 09:11 UTC, dvanhout89 approved these changes

2024-05-20 09:13 UTC, DewanAlberts approved these changes

2024-05-20 09:57 UTC, Juanro-Minne approved these changes

2024-05-20 10:27 UTC, merged