Joe/employe dto refractor
RetroRabbit/RGO-Server pull request #11
Opened 2024-02-27 12:04 UTC by KAYEMBAJONATHAN

Refactoring the employee Dto

All related unit tests are passing

2024-02-27 12:21 UTC, Juanro-Minne commented on RGO.App.Tests/Controllers/HRIS/EmployeeRoleManagerControllerUnitTests.cs
> +        roleServiceMock.Setup(x => x.GetRole(role)).ReturnsAsync(new RoleDto{ Id = 0, Description = "Super Admin" });
Just double check that you initialize the correct values everywhere
(Id was 1 you initialized it as 0)

2024-02-27 12:22 UTC, Juanro-Minne commented on RGO.Services.Tests/Handler/Charts/SalaryTypeUnitTest.cs
> +        roleDto = new RoleDto{ Id = 0, Description = "Employee"};
Initial value was 3

2024-02-28 06:07 UTC, Juanro-Minne approved these changes

2024-02-28 06:09 UTC, Juanro-Minne commented on RGO.App.Tests/Controllers/HRIS/EmployeeRoleManagerControllerUnitTests.cs
> +            new RoleDto{ Description = "Super Admin" },
```suggestion
            new RoleDto{ Id = 1, Description = "Super Admin" },
```

2024-02-28 06:10 UTC, Juanro-Minne commented on RGO.App.Tests/Controllers/HRIS/EmployeeRoleManagerControllerUnitTests.cs
> +            new RoleDto{Id = 1, Description = "Admin"},
this id needs to be 2
```suggestion
            new RoleDto{Id = 2, Description = "Admin"},
```

2024-02-28 06:13 UTC, Juanro-Minne approved these changes

2024-02-28 09:15 UTC, EstiaanBritz approved these changes

2024-02-28 09:31 UTC, tbddorothy requested changes

2024-02-28 09:31 UTC, tbddorothy commented on RGO.Services.Tests/Services/EmployeeRoleServiceUnitTest.cs
> +        _ = Assert.ThrowsAsync<Exception>(() => _employeeRoleService.UpdateEmployeeRole(new EmployeeRoleDto
```suggestion
        Assert.ThrowsAsync<Exception>(() => _employeeRoleService.UpdateEmployeeRole(new EmployeeRoleDto
```

2024-02-28 09:41 UTC, Juanro-Minne approved these changes

2024-02-28 09:53 UTC, KAYEMBAJONATHAN commented on RGO.Services.Tests/Services/EmployeeRoleServiceUnitTest.cs
> +        _ = Assert.ThrowsAsync<Exception>(() => _employeeRoleService.UpdateEmployeeRole(new EmployeeRoleDto
@tbddorothy  fixed

2024-02-28 10:11 UTC, KAYEMBAJONATHAN commented on RGO.Services.Tests/Services/EmployeeRoleServiceUnitTest.cs
>          };
alaright

2024-02-28 11:25 UTC, tbddorothy approved these changes

2024-02-28 11:26 UTC, tbddorothy approved these changes

2024-02-28 11:31 UTC, Juanro-Minne approved these changes

2024-02-28 11:35 UTC, EstiaanBritz approved these changes

2024-02-28 11:36 UTC, EstiaanBritz approved these changes

2024-02-28 12:37 UTC, ReinoRabbit approved these changes

2024-02-28 12:38 UTC, merged