Dev | Program.cs Refactor
RetroRabbit/RGO-Server pull request #170
Opened 2024-07-01 10:12 UTC by bseptember

### Overview:

The Main method was over 200 lines. We needed to refactor the setup code.
Place them in their own related methods so its not hard to follow the code.

**Note: Please test on your side before approval.**

[Dev 9572](
https://dev.azure.com/retro-rabbit/RetroGradOnboard/_boards/board/t/RetroGradOnboard%20Team/Stories?System.AssignedTo=%40me&workitem=9572)

2024-07-01 13:25 UTC, Wimmas approved these changes

2024-07-02 09:37 UTC, EduanO commented on RR.App/Program.cs
> +                        if (policySettings.Permissions?.Any() == true)
```suggestion
                        if (policySettings.Permissions.Any() == true)
```

2024-07-02 09:47 UTC, EduanO requested changes
Please look at comments

2024-07-02 09:47 UTC, EduanO commented on RR.App/Program.cs
> +            policies.ForEach(policySettings =>
```suggestion
            policies?.ForEach(policySettings =>
```

2024-07-02 09:47 UTC, EduanO commented on RR.App/Program.cs
> +                            LazyJsonWebKeySet.Value?.Keys ?? throw new InvalidOperationException("JsonWebKeySet is not available.")
```suggestion
                            LazyJsonWebKeySet.Value.Keys ?? throw new InvalidOperationException("JsonWebKeySet is not available.")
```

2024-07-02 09:47 UTC, EduanO commented on RR.App/Program.cs
>                          IssuerSigningKeyResolver = (token, securityToken, kid, validationParameters) =>
```suggestion
                        IssuerSigningKeyResolver = (_, _, _, _) =>
```

2024-07-02 09:47 UTC, EduanO commented on RR.App/Program.cs
> +                        if (policySettings.Permissions?.Any() == true)
```suggestion
                         if (policySettings.Permissions.Any())
```

2024-07-02 09:47 UTC, EduanO commented on RR.App/Program.cs
> +            ConfigureConfigurationSources(configuration);
```suggestion
            SetupConfiguration(configuration);
```

2024-07-02 09:47 UTC, EduanO commented on RR.App/Program.cs
> +        private static void ConfigureConfigurationSources(ConfigurationManager configuration)
```suggestion
        private static void SetupConfiguration(ConfigurationManager configuration)
```

2024-07-02 09:47 UTC, EduanO commented on RR.App/Program.cs
> +        private static void RegisterServices(IServiceCollection services, IConfiguration configuration)
```suggestion
        private static void SetupDependencyInjection(IServiceCollection services, IConfiguration configuration)
```

2024-07-02 09:47 UTC, EduanO commented on RR.App/Program.cs
> +            RegisterServices(builder.Services, configuration);
```suggestion
            SetupDependencyInjection(builder.Services, configuration);
```

2024-07-03 13:56 UTC, MathildaShongwe15 approved these changes

2024-07-03 14:00 UTC, madwizzard approved these changes

2024-07-03 20:38 UTC, merged