DEV | Property Access Controller
RetroRabbit/RGO-Server pull request #179
Opened 2024-07-04 11:40 UTC by bseptember

Overview

Added middleware unit test helper.
Removed try catch blocks.
Removed redundant if statements.
Fixed unit tests accordingly.

[Azure board](https://dev.azure.com/retro-rabbit/RetroGradOnboard/_sprints/taskboard/RetroGradOnboard%20Team/RetroGradOnboard/Sprint%2024?workitem=9662)

![image](https://github.com/RetroRabbit/RGO-Server/assets/68727050/e30a6b41-0c2f-4b6c-97f4-99a8830462b7)

2024-07-04 11:52 UTC, MathildaShongwe15 approved these changes, later dismissed

2024-07-04 11:53 UTC, Juanro-Minne approved these changes, later dismissed

2024-07-04 12:12 UTC, madwizzard submitted a review, later dismissed

2024-07-04 12:35 UTC, EduanO requested changes

2024-07-04 12:35 UTC, EduanO commented on RR.App/Controllers/HRIS/PropertyAccessController.cs
> +        throw new CustomException("Error retrieving employee.");
Reducing the nested if statements can make it easier to read. I'm suggesting an additional check to see if employee exist before we return their id. Prevents null reference exceptions.

```
if (string.IsNullOrEmpty(_identity.Email)) 
    throw new CustomException("Error retrieving employee.");

if (email == _identity.Email)
    return Ok(_identity.EmployeeId);

if (_identity.Role is not ("SuperAdmin" or "Admin" or "Talent" or "Journey"))
    throw new CustomException("Error retrieving employee.");

var employee = await _employeeService.GetEmployee(email);
return employee == null 
    ? throw new CustomException("Error retrieving employee.") 
    : Ok(employee.Id);
```

2024-07-04 12:35 UTC, EduanO commented on RR.App.Tests/Controllers/HRIS/PropertyAccessControllerUnitTests.cs
> +    private readonly Mock<AuthorizeIdentity> _authorizeIdentityMock;
This variable is referenced but never used.

2024-07-04 12:35 UTC, EduanO commented on RR.App.Tests/Controllers/HRIS/PropertyAccessControllerUnitTests.cs
> +        _propertyAccessController = new PropertyAccessController(new AuthorizeIdentityMock(1), _propertyAccessMockService.Object, _employeeMockService.Object);
Either use `AuthorizeIdentityMock` or `Mock<AuthorizeIdentity>`  in your tests. I see you using both. 

Just for consistency.

2024-07-04 13:24 UTC, madwizzard approved these changes, later dismissed

2024-07-04 13:25 UTC, Juanro-Minne submitted a review, later dismissed

2024-07-04 13:37 UTC, EduanO submitted a review, later dismissed

2024-07-05 07:06 UTC, MathildaShongwe15 approved these changes, later dismissed

2024-07-05 07:16 UTC, KAYEMBAJONATHAN approved these changes, later dismissed

2024-07-05 07:30 UTC, KAYEMBAJONATHAN approved these changes

2024-07-05 07:31 UTC, MathildaShongwe15 approved these changes

2024-07-05 07:31 UTC, bseptember commented
Thank you @MathildaShongwe15  for pointing out the other controller instantiation which was unnecessary.👍

2024-07-05 07:38 UTC, EduanO approved these changes

2024-07-05 07:49 UTC, Juanro-Minne approved these changes

2024-07-05 07:51 UTC, merged