Wimpie/employee certificate controller refactor
RetroRabbit/RGO-Server pull request #184
Opened 2024-07-05 10:01 UTC by Wimmas

![image](https://github.com/RetroRabbit/RGO-Server/assets/8805239/7ad537c0-d4b4-4f15-9f2f-e9a92b8969f7)

2024-07-05 10:22 UTC, bseptember requested changes

2024-07-05 10:22 UTC, bseptember commented on RR.App.Tests/Controllers/HRIS/EmployeeCertificationControllerUnitTests.cs
>  using Xunit;
Clean: are all these necessary?

2024-07-05 10:22 UTC, bseptember commented on RR.App/Controllers/HRIS/EmployeeCertificationController.cs
>              }
Refactor: can this be reduced?

2024-07-05 10:22 UTC, bseptember commented on RR.App/Controllers/HRIS/EmployeeCertificationController.cs
> +                throw new CustomException("User data being accessed does not match user making the request.");
Refactor: can this be reduced?

2024-07-05 10:46 UTC, EduanO commented on RR.App/Controllers/HRIS/EmployeeCertificationController.cs
>              }
```if (_identity.Role is not ("SuperAdmin" or "Admin" or "Talent" or "Journey") && employeeId != _identity.EmployeeId)
    throw new CustomException("Unauthorized Access.");```

2024-07-05 10:48 UTC, EduanO commented on RR.App/Controllers/HRIS/EmployeeCertificationController.cs
> +                throw new CustomException("User data being accessed does not match user making the request.");
```
if (_identity.Role is not ("SuperAdmin" or "Admin" or "Talent" or "Journey") && employeeId != _identity.EmployeeId)
    throw new CustomException("Unauthorized Access.");
```

2024-07-05 10:52 UTC, EduanO requested changes
Please reduce the nested if statements on the controllers. I left a comment for how it can be changed.

For the unit tests, please fix the names of the methods. They have Typo's:
Employee**l**Certi**i**ficates

2024-07-05 12:13 UTC, Wimmas commented on RR.App/Controllers/HRIS/EmployeeCertificationController.cs
>              }
Done

2024-07-05 12:14 UTC, Wimmas commented on RR.App/Controllers/HRIS/EmployeeCertificationController.cs
> +                throw new CustomException("User data being accessed does not match user making the request.");
Done

2024-07-05 12:15 UTC, Wimmas commented on RR.App.Tests/Controllers/HRIS/EmployeeCertificationControllerUnitTests.cs
>  using Xunit;
Done

2024-07-05 12:54 UTC, EduanO approved these changes

2024-07-05 19:11 UTC, bseptember approved these changes

2024-07-09 08:21 UTC, madwizzard approved these changes

2024-07-09 08:33 UTC, merged