Reino/employee date controller
RetroRabbit/RGO-Server pull request #192
Opened 2024-07-08 09:13 UTC by ReinoRabbit

- Refactored the employee date controller
- Updated the unit tests for the controller to accommodate for the middleware

**Coverage Report**

![image](https://github.com/RetroRabbit/RGO-Server/assets/156097906/14331ac7-d276-4355-90b0-03bb2693b9ae)

2024-07-08 12:00 UTC, bseptember requested changes, later dismissed

2024-07-08 12:00 UTC, bseptember commented on RR.App.Tests/Controllers/HRIS/EmployeeDateControllerUnitTests.cs
> -
Fix: refer to  [UpdatePropertyRoleAccessReturnsSuccess line 130](https://github.com/RetroRabbit/RGO-Server/blob/df46ce432a2a34cf1c79aaf8b5eefd65c5731d24/RR.App.Tests/Controllers/HRIS/PropertyAccessControllerUnitTests.cs#L130) ,  [UpdatePropertyRoleAccessReturnsFail line 143](https://github.com/RetroRabbit/RGO-Server/blob/df46ce432a2a34cf1c79aaf8b5eefd65c5731d24/RR.App.Tests/Controllers/HRIS/PropertyAccessControllerUnitTests.cs#L143)

and the controller [UpdatePropertyRoleAccess line 45](https://github.com/RetroRabbit/RGO-Server/blob/df46ce432a2a34cf1c79aaf8b5eefd65c5731d24/RR.App/Controllers/HRIS/PropertyAccessController.cs#L45)

Include tests for success and failure. Fix the others as well below please.

2024-07-08 18:34 UTC, EduanO requested changes
This work is incomplete. We do not allow any logical/business implementation on the controller. We require this to be in a service.

2024-07-16 13:24 UTC, DewanAlberts approved these changes

2024-07-16 14:18 UTC, Juanro-Minne approved these changes

2024-07-17 06:11 UTC, EduanO requested changes

2024-07-17 06:11 UTC, EduanO commented on RR.App/Controllers/HRIS/EmployeeDateController.cs
>      public EmployeeDateController(IEmployeeDateService employeeDateService, IEmployeeService employeeService)
```suggestion
    public EmployeeDateController(IEmployeeDateService employeeDateService)
```

2024-07-17 07:16 UTC, EduanO approved these changes

2024-07-17 07:18 UTC, merged