Gesterhuyse/role management refactor
RetroRabbit/RGO-Server pull request #196
Opened 2024-07-10 08:20 UTC by SuperSouls

Refactored Role Access Manage Controller and the Role Access Manage Controller Unit Test.

![image](https://github.com/RetroRabbit/RGO-Server/assets/122920681/1cbf6d80-e2a5-4146-b74e-ad0abac8f9a6)
![image](https://github.com/RetroRabbit/RGO-Server/assets/122920681/434d0c62-a752-4885-86fd-87d27e1bd1db)

2024-07-10 17:25 UTC, EduanO requested changes

2024-07-10 17:25 UTC, EduanO commented on RR.App/Controllers/HRIS/RoleManageController.cs
> +using HRIS.Services.Services;
```suggestion
```

2024-07-10 17:25 UTC, EduanO commented on RR.App/Controllers/HRIS/RoleManageController.cs
> +    private readonly AuthorizeIdentity _identity;
```suggestion
```

2024-07-10 17:25 UTC, EduanO commented on RR.App/Controllers/HRIS/RoleManageController.cs
>      private readonly IRoleService? _roleService;
```suggestion
    private readonly IRoleAccessLinkService _roleAccessLinkService;
    private readonly IRoleAccessService _roleAccessService;
    private readonly IRoleService _roleService;
```

I'm not sure why these services are marked as nullable - Should never be nullable. Please change this as well.

2024-07-10 17:25 UTC, EduanO commented on RR.App/Controllers/HRIS/RoleManageController.cs
>                  : await _roleService.SaveRole(new RoleDto{ Id = 0, Description = role});
```suggestion
```

Please remove all unused code

Also please indent your code. `CTRL + K + D`

2024-07-11 06:45 UTC, EduanO requested changes

2024-07-11 06:45 UTC, EduanO commented on RR.App/Controllers/HRIS/RoleManageController.cs
>          IRoleAccessLinkService? roleAccessLinkService,
```suggestion
        IRoleAccessLinkService roleAccessLinkService,
```

This also needs to change. Should not be nullable types

2024-07-11 07:12 UTC, EduanO approved these changes

2024-07-11 07:16 UTC, ReitumetseMoloto approved these changes

2024-07-11 07:16 UTC, MathildaShongwe15 approved these changes

2024-07-11 07:17 UTC, merged