Fix/user secrets
RetroRabbit/RGO-Server pull request #199
Opened 2024-07-10 15:31 UTC by nzikalala

2024-07-10 17:30 UTC, EduanO requested changes
Minor code clean-up but overall happy with implementation

2024-07-10 17:30 UTC, EduanO commented on HRIS.Models/AuthManagement.cs
> +
```suggestion
```

2024-07-10 17:30 UTC, EduanO commented on HRIS.Models/SMTPSettings.cs
> +
```suggestion
```

2024-07-10 17:30 UTC, EduanO commented on HRIS.Services.Tests/Helpers/EmailHelperUnitTests.cs
> +    /*private readonly Mock<IOptions<SMTPSettings>> _smtp;*/
```suggestion
```

2024-07-10 17:30 UTC, EduanO commented on HRIS.Services.Tests/Helpers/EmailHelperUnitTests.cs
> +
```suggestion
        var smtp = Options.Create(new SMTPSettings{
            Name = "test",
            Host = "testHost",
            Mail = "testMail@retrorabbit.co.za",
            Password = "password",
            Port = "54"
        });

        _helper = new EmailHelper(_db.Object, smtp);
```

2024-07-10 17:30 UTC, EduanO commented on RR.App/Program.cs
> +
```suggestion

```

2024-07-11 06:25 UTC, MathildaShongwe15 submitted a review, later dismissed

2024-07-11 06:25 UTC, ReitumetseMoloto approved these changes, later dismissed

2024-07-11 08:45 UTC, bseptember requested changes

2024-07-11 08:45 UTC, bseptember commented on HRIS.Services/Services/AuthService.cs
> +            { "audience", $"{_authManagement.Issuer ?? EnvironmentVariableHelper.AUTH_MANAGEMENT_ISSUER}api/v2/" }
Refactor: can this entire thing perhaps be a variable set once in the constructor?

string _clientId = _authManagement.ClientId ?? EnvironmentVariableHelper.AUTH_MANAGEMENT_CLIENT_ID;

Same applies to rest of code.

2024-07-12 07:16 UTC, bseptember approved these changes, later dismissed
@EduanO @nzikalala once merged, we need to check **the server** if this breaks. If it does, then all the values must be swapped around:
eg.
this
_smtpSettings.Password ?? EnvironmentVariableHelper.SMTP_PASSWORD
to
EnvironmentVariableHelper.SMTP_PASSWORD ??_smtpSettings.Password
and so on.

2024-07-12 07:57 UTC, EduanO approved these changes

2024-07-12 08:59 UTC, EduanO approved these changes

2024-07-12 09:01 UTC, MathildaShongwe15 approved these changes

2024-07-12 09:04 UTC, ReitumetseMoloto approved these changes

2024-07-12 09:04 UTC, merged