Juanro/remove projectservice
RetroRabbit/RGO-Server pull request #209
Opened 2024-07-19 09:08 UTC by Juanro-Minne

![image](https://github.com/user-attachments/assets/0d2ae201-8a58-4e0f-98d1-31a92262ff8a)
project service was not being used anywhere only references it has were within it service or the interface itself

2024-07-19 09:25 UTC, ReinoRabbit approved these changes

2024-07-19 10:47 UTC, EduanO requested changes
When you remove an Entity class you must run a Migration to update the DB to remove that table.

2024-07-19 11:04 UTC, Juanro-Minne commented
> When you remove an Entity class you must run a Migration to update the DB to remove that table.

I did not think of that thanks

2024-07-22 06:06 UTC, madwizzard approved these changes

2024-07-22 06:46 UTC, EduanO approved these changes

2024-07-22 12:41 UTC, merged