Juanro/employeedate service refactor
RetroRabbit/RGO-Server pull request #210
Opened 2024-07-22 13:12 UTC by Juanro-Minne

- added logic checks for role and model existing
- checked to stop self termination
- updated unit tests
- added fail case tests
- refactored termination service

2024-07-22 14:02 UTC, madwizzard commented on HRIS.Services.Tests/Services/TerminationServiceUnitTests.cs
> +
```suggestion
```

2024-07-22 14:21 UTC, madwizzard approved these changes

2024-07-22 21:35 UTC, EduanO requested changes

2024-07-22 21:35 UTC, EduanO commented on HRIS.Services.Tests/Services/TerminationServiceUnitTests.cs
> +using HRIS.Models;
```suggestion
```

2024-07-22 21:35 UTC, EduanO commented on HRIS.Services.Tests/Services/TerminationServiceUnitTests.cs
>      private readonly EmployeeType _employeeTypeDto;
```suggestion
    private readonly Employee _employee;
    private readonly EmployeeDate _employeeDate;
    private readonly EmployeeType _employeeType;
```

2024-07-22 21:35 UTC, EduanO commented on HRIS.Services.Tests/Services/TerminationServiceUnitTests.cs
> +        _employeeDate = new EmployeeDate();
```suggestion
```

2024-07-22 21:35 UTC, EduanO commented on HRIS.Services.Tests/Services/TerminationServiceUnitTests.cs
> +        int testId = 1;
```suggestion
        var testId = 1;
```

2024-07-22 21:35 UTC, EduanO commented on HRIS.Services.Tests/Services/TerminationServiceUnitTests.cs
> +        int testId = 1;
```suggestion
        var testId = 1;
```

2024-07-22 21:35 UTC, EduanO commented on HRIS.Services/Services/TerminationService.cs
> +    public async Task<bool> CheckIfModelExists(int id)
```suggestion
    public async Task<bool> TerminationExists(int id)
```

2024-07-22 21:35 UTC, EduanO commented on HRIS.Services/Services/TerminationService.cs
>      public async Task<TerminationDto> SaveTermination(TerminationDto terminationDto)
```suggestion
    public async Task<TerminationDto> CreateTermination(TerminationDto terminationDto)
```

2024-07-22 21:35 UTC, EduanO commented on HRIS.Services/Interfaces/ITerminationService.cs
> +    /// <summary>
```suggestion
    /// <summary>
    ///     Update an existing termination.
    /// </summary>
    /// <param name="terminationDto">The Termination DTO.</param>
    /// <returns>The updated Termination DTO.</returns>
    Task<TerminationDto> UpdateTerminationAsync(TerminationDto terminationDto);
    
    /// <summary>
```

2024-07-23 05:48 UTC, MathildaShongwe15 reviewed
Coverage report not attached.

2024-07-23 07:00 UTC, Juanro-Minne commented
> Coverage report not attached.

attached

2024-07-23 07:14 UTC, MathildaShongwe15 approved these changes

2024-07-23 07:53 UTC, EduanO approved these changes

2024-07-23 07:58 UTC, merged