Employee banking controller refactor & Unit tests
RetroRabbit/RGO-Server pull request #211
Opened 2024-07-22 13:36 UTC by DewanAlberts

![image](https://github.com/user-attachments/assets/4f9eef97-167c-44d9-bd08-7feb71d280ca)

2024-07-22 13:51 UTC, Juanro-Minne commented on RR.App.Tests/Controllers/HRIS/EmployeeBankingControllerUnitTests.cs
> +        _identity.SetupGet(i => i.Email).Returns("talent@example.com");
maybe setup the _identity at class level
![image](https://github.com/user-attachments/assets/d257d03e-cf83-4c1c-81be-870e3768a312)

2024-07-22 21:16 UTC, EduanO requested changes

2024-07-22 21:16 UTC, EduanO commented on HRIS.Services/Services/EmployeeBankingService.cs
> +using Microsoft.EntityFrameworkCore.Update;
```suggestion
```

2024-07-22 21:16 UTC, EduanO commented on HRIS.Services/Services/EmployeeBankingService.cs
> +        };
```suggestion
```

2024-07-22 21:16 UTC, EduanO commented on HRIS.Services/Services/EmployeeBankingService.cs
> +
```suggestion
```

2024-07-22 21:16 UTC, EduanO commented on RR.App.Tests/Controllers/HRIS/EmployeeBankingControllerUnitTests.cs
> +using Microsoft.AspNetCore.Http.HttpResults;
```suggestion
```

2024-07-22 21:16 UTC, EduanO commented on RR.App.Tests/Controllers/HRIS/EmployeeBankingControllerUnitTests.cs
> +    private readonly AuthorizeIdentityMock _identity;
```suggestion
```

2024-07-22 21:16 UTC, EduanO commented on RR.App/Controllers/HRIS/EmployeeBankingController.cs
> +        var claimsIdentity = User.Identity as ClaimsIdentity;
```suggestion
```

2024-07-22 21:16 UTC, EduanO commented on RR.App/Controllers/HRIS/EmployeeBankingController.cs
> +            await _employeeBankingService.Save(newEntry, claimsIdentity!.FindFirst(ClaimTypes.Email)!.Value);
```suggestion
            await _employeeBankingService.Save(newEntry, _identity.Email);
```

2024-07-22 21:16 UTC, EduanO commented on RR.App/Controllers/HRIS/EmployeeBankingController.cs
> +        var claimsIdentity = User.Identity as ClaimsIdentity;
```suggestion
```

2024-07-22 21:16 UTC, EduanO commented on RR.App/Controllers/HRIS/EmployeeBankingController.cs
> +        await _employeeBankingService.Update(updateEntry, claimsIdentity!.FindFirst(ClaimTypes.Email)!.Value);
```suggestion
        await _employeeBankingService.Update(updateEntry, _identity.Email);
```

2024-07-22 21:16 UTC, EduanO commented on RR.App/Controllers/HRIS/EmployeeBankingController.cs
> +        if (_identity.Role is not ("SuperAdmin" or "Admin") || _identity.EmployeeId != id)
```suggestion
        if (_identity.Role is not ("SuperAdmin" or "Admin") && _identity.EmployeeId != id)
```

2024-07-23 07:54 UTC, EduanO approved these changes

2024-07-23 07:58 UTC, ReinoRabbit approved these changes

2024-07-23 08:00 UTC, Juanro-Minne approved these changes

2024-07-23 08:33 UTC, merged