Employee Qualification Service Refactoring
RetroRabbit/RGO-Server pull request #215
Opened 2024-07-24 07:36 UTC by MathildaShongwe15

![image](https://github.com/user-attachments/assets/6b05e1d2-d226-47c4-b161-570c660b8e4a)

2024-07-24 16:47 UTC, EduanO requested changes

2024-07-24 16:47 UTC, EduanO commented on HRIS.Services.Tests/Services/EmployeeQualificationServiceUnitTests.cs
> +
```suggestion
```

2024-07-24 16:47 UTC, EduanO commented on HRIS.Services.Tests/Services/EmployeeQualificationServiceUnitTests.cs
> +    }
```suggestion
    }
    
```

2024-07-24 16:47 UTC, EduanO commented on HRIS.Services.Tests/Services/EmployeeQualificationServiceUnitTests.cs
> +    #endregion
```suggestion
    #endregion
    
```

2024-07-24 16:47 UTC, EduanO commented on HRIS.Services.Tests/Services/EmployeeQualificationServiceUnitTests.cs
> +    public async Task UpdateEmployeeQaulification_DoesNotExist()
```suggestion
    public async Task UpdateEmployeeQualification_DoesNotExist()
```

2024-07-24 16:47 UTC, EduanO commented on HRIS.Services/Interfaces/IEmployeeQualificationService.cs
> +    /// <param name="email"></param>
```suggestion
    /// <param name="id"></param>
```

2024-07-24 16:47 UTC, EduanO commented on HRIS.Services/Interfaces/IEmployeeQualificationService.cs
> +    Task<bool> CheckIfExists(int Id);
```suggestion
    Task<bool> CheckIfExists(int id);
```

2024-07-24 16:47 UTC, EduanO commented on HRIS.Services/Services/EmployeeQualificationService.cs
> +    public async Task<bool> CheckIfExists(int Id)
```suggestion
    public async Task<bool> CheckIfExists(int id)
```

2024-07-25 14:14 UTC, bseptember requested changes
Please note, you'll need to add a null check unit test for those suggested changes.

2024-07-25 14:14 UTC, bseptember commented on HRIS.Services/Services/EmployeeQualificationService.cs
> +        return qualifications.ToDto();
```suggestion
     if (qualifications == null)
         throw new CustomException("No employee qualifications data.");

     return qualifications.ToDto();
```

2024-07-25 14:14 UTC, bseptember commented on HRIS.Services/Services/EmployeeQualificationService.cs
```suggestion
      if (qualification == null)
          throw new CustomException("No employee qualification data.");
```

2024-07-25 17:45 UTC, EduanO approved these changes

2024-07-26 07:03 UTC, bseptember approved these changes

2024-07-26 07:10 UTC, ReitumetseMoloto approved these changes

2024-07-26 07:49 UTC, merged