Bseptember/authservice refactor
RetroRabbit/RGO-Server pull request #217
Opened 2024-07-24 10:53 UTC by bseptember

2024-07-24 12:07 UTC, Wimmas approved these changes

2024-07-24 14:45 UTC, madwizzard commented on HRIS.Services.Tests/Services/AuthServiceUnitTest.cs
> +        // Note for developer: We use an asymmetric key, but for testing we can simply use a symmetric key!
```suggestion
```

2024-07-24 17:03 UTC, EduanO requested changes

2024-07-24 17:03 UTC, EduanO commented on HRIS.Services/Services/AuthService.cs
> +    private HttpClient _httpClient;
```suggestion
    private readonly string _clientId;
    private readonly string _clientSecret;
    private readonly string _issuer;
    private readonly string _audience;
    private readonly HttpClient _httpClient;
```

2024-07-24 17:03 UTC, EduanO commented on HRIS.Services/Services/AuthService.cs
> +    private readonly IManagementApiClient _managementApiClient;
```suggestion
```

2024-07-24 17:03 UTC, EduanO commented on HRIS.Services/Services/AuthService.cs
> +        _httpClient = new HttpClient();
```suggestion
        var authManagement = options.Value;
        _clientId = authManagement.ClientId ?? EnvironmentVariableHelper.AUTH_MANAGEMENT_CLIENT_ID;
        _clientSecret = authManagement.ClientSecret ?? EnvironmentVariableHelper.AUTH_MANAGEMENT_CLIENT_SECRET;
        _issuer = authManagement.Issuer ?? EnvironmentVariableHelper.AUTH_MANAGEMENT_ISSUER;
        _audience = authManagement.Audience ?? EnvironmentVariableHelper.AUTH_MANAGEMENT_AUDIENCE;
        _cachedAccessToken = string.Empty;
        _managementApiClient = new ManagementApiClient(_cachedAccessToken, new Uri($"{_issuer}api/v2"));
        _httpClient = new HttpClient();
```

2024-07-24 17:03 UTC, EduanO commented on HRIS.Services/Services/AuthService.cs
> +        _httpClient = new HttpClient();
Can be a local variable in constructor

2024-07-24 17:03 UTC, EduanO commented on HRIS.Services/Services/AuthService.cs
> +        var jsonDoc = System.Text.Json.JsonDocument.Parse(content);
```suggestion
        var jsonDoc = JsonDocument.Parse(content);
```

2024-07-24 17:03 UTC, EduanO commented on HRIS.Services/Services/AuthService.cs
> +    public async Task<IPagedList<Auth0.ManagementApi.Models.Role>> GetAllRolesAsync()
```suggestion
    public async Task<IPagedList<Role>> GetAllRolesAsync()
```

2024-07-24 17:03 UTC, EduanO commented on HRIS.Services/Services/AuthService.cs
> +    public async Task<IPagedList<Auth0.ManagementApi.Models.User>> GetAllUsersAsync()
```suggestion
    public async Task<IPagedList<User>> GetAllUsersAsync()
```

2024-07-24 17:03 UTC, EduanO commented on HRIS.Services/Services/AuthService.cs
> +    public async Task<IList<Auth0.ManagementApi.Models.User>> GetUsersByEmailAsync(string email)
```suggestion
    public async Task<IList<User>> GetUsersByEmailAsync(string email)
```

2024-07-24 17:03 UTC, EduanO commented on HRIS.Services/Services/AuthService.cs
> +    public async Task<IPagedList<Auth0.ManagementApi.Models.AssignedUser>> GetUsersByRoleAsync(string roleId)
```suggestion
    public async Task<IPagedList<AssignedUser>> GetUsersByRoleAsync(string roleId)
```

2024-07-24 17:03 UTC, EduanO commented on HRIS.Services/Services/AuthService.cs
> +    public async Task<IPagedList<Auth0.ManagementApi.Models.Role>> GetUserRolesAsync(string userId)
```suggestion
    public async Task<IPagedList<Role>> GetUserRolesAsync(string userId)
```

2024-07-24 17:03 UTC, EduanO commented on HRIS.Services/Services/AuthService.cs
> +        var temporaryRole = await _managementApiClient.Roles.UpdateAsync(roleId, new RoleUpdateRequest
```suggestion
        await _managementApiClient.Roles.UpdateAsync(roleId, new RoleUpdateRequest
```

2024-07-24 17:03 UTC, EduanO commented on HRIS.Services/Services/AuthService.cs
> +        var existingUser = await _managementApiClient.Users.GetAsync(userId, null, true);
```suggestion
        var existingUser = await _managementApiClient.Users.GetAsync(userId);
```

2024-07-24 17:03 UTC, EduanO commented on HRIS.Services/Services/AuthService.cs
> +        var existingUser = await _managementApiClient.Users.GetAsync(userId, null, true);
They are already set to default `null` and `true`

2024-07-25 04:13 UTC, nzikalala approved these changes

2024-07-25 13:45 UTC, bseptember commented on HRIS.Services/Services/AuthService.cs
> +    private readonly IManagementApiClient _managementApiClient;
@EduanO  is this a mistake? _managementApiClient is required in the code

2024-07-25 17:43 UTC, EduanO commented on HRIS.Services/Services/AuthService.cs
> +    private readonly IManagementApiClient _managementApiClient;
Yeah not sure where I was going with that. My bad.

2024-07-25 17:43 UTC, EduanO approved these changes

2024-07-26 07:05 UTC, merged