Employee certification service refactor
RetroRabbit/RGO-Server pull request #219
Opened 2024-07-25 06:02 UTC by KAYEMBAJONATHAN

- Add refactor employee certification service 
- Add Update unit test
- Add mock new unit test to cover all the line
![Screenshot 2024-07-25 073740](https://github.com/user-attachments/assets/2a023514-bdf2-4631-82ad-9639aa55936b)

2024-07-25 15:36 UTC, bseptember requested changes
@KAYEMBAJONATHAN you need to add two additional unit tests to check identity role. 
for SaveEmployeeCertification & GetEmployeeCertification

2024-07-25 15:36 UTC, bseptember commented on HRIS.Services/Services/EmployeeCertificationService.cs
> +        }
```suggestion
        if (!_identity.IsSupport && employeeCertificationDto.Id != _identity.EmployeeId)
            throw new CustomException("Unauthorized access.");
```

2024-07-25 15:36 UTC, bseptember commented on HRIS.Services/Services/EmployeeCertificationService.cs
> +        }
```suggestion
        if (!_identity.IsSupport && employeeCertificationDto.Id != _identity.EmployeeId)
            throw new CustomException("Unauthorized access.");
```

2024-07-25 15:36 UTC, bseptember commented on HRIS.Services/Services/EmployeeCertificationService.cs
> +    public async Task<EmployeeCertificationDto> DeleteEmployeeCertification(int Id)
```suggestion
    public async Task<EmployeeCertificationDto> DeleteEmployeeCertification(int id)
```

2024-07-25 15:36 UTC, bseptember commented on HRIS.Services/Services/EmployeeCertificationService.cs
> +        var exists = await CheckIfCertificationExists(Id);
```suggestion
        var exists = await CheckIfCertificationExists(id);
```

2024-07-25 15:36 UTC, bseptember commented on HRIS.Services/Services/EmployeeCertificationService.cs
> +        }
```suggestion
        if (!_identity.IsSupport && id != _identity.EmployeeId)
            throw new CustomException("Unauthorized access.");
```

2024-07-25 15:36 UTC, bseptember commented on HRIS.Services/Services/EmployeeCertificationService.cs
> +        return (await _db.EmployeeCertification.Delete(Id)).ToDto();
```suggestion
        return (await _db.EmployeeCertification.Delete(id)).ToDto();
```

2024-07-25 15:36 UTC, bseptember commented on HRIS.Services/Services/EmployeeCertificationService.cs
```suggestion
        if (!_identity.IsSupport && employeeId != _identity.EmployeeId)
            throw new CustomException("Unauthorized access.");
```

2024-07-25 15:36 UTC, bseptember commented on HRIS.Services/Services/EmployeeCertificationService.cs
> +
```suggestion
        if (!_identity.IsSupport && employeeId != _identity.EmployeeId)
            throw new CustomException("Unauthorized access.");
```

2024-07-25 17:40 UTC, EduanO requested changes

2024-07-25 17:40 UTC, EduanO commented on HRIS.Services.Tests/Services/EmployeeCertificationServiceUnitTests.cs
>  using HRIS.Services.Interfaces;
```suggestion
```

2024-07-25 17:40 UTC, EduanO commented on HRIS.Services/Services/EmployeeCertificationService.cs
Please fix naming conventions on methods

`SaveEmployeeCertification` -> `CreateEmployeeCertification`
`GetEmployeeCertification` -> `GetEmployeeCertificationByEmployeeIdAndCertificationId`
`GetAllEmployeeCertifications` -> `GetEmployeeCertificationsByEmployeeId`

2024-07-26 08:59 UTC, KAYEMBAJONATHAN commented
![Screenshot 2024-07-26 105338](https://github.com/user-attachments/assets/2656a6b9-960f-4b71-b200-265050a02830)

2024-07-26 09:25 UTC, bseptember approved these changes

2024-07-26 10:57 UTC, nzikalala approved these changes

2024-07-29 07:13 UTC, EduanO approved these changes

2024-07-29 07:17 UTC, merged