Reino/employee data service refactor
RetroRabbit/RGO-Server pull request #220
Opened 2024-07-25 07:59 UTC by ReinoRabbit

**Refactored the Employee Data Service**

- Added authorization checks
- Added checks to see if models exist
- Updated the unit tests

![image](https://github.com/user-attachments/assets/f2ef7942-e7ae-4c67-a752-0bb5afd26575)

2024-07-25 10:01 UTC, Juanro-Minne approved these changes

2024-07-25 13:47 UTC, madwizzard approved these changes

2024-07-25 17:35 UTC, EduanO requested changes
Please go fix the logic of querying the data. We should not pull all data and then filter from them. 

Fix method naming.

Apply logical checks as shown in the diagram on the user story.

2024-07-29 07:15 UTC, EduanO approved these changes

2024-07-29 07:54 UTC, EduanO requested changes
Please look at using directives as well.

2024-07-29 07:54 UTC, EduanO commented on HRIS.Services.Tests/Services/EmployeeDataServiceUnitTest.cs
> +    //}
Ghost code

2024-07-29 09:48 UTC, ReinoRabbit commented on HRIS.Services.Tests/Services/EmployeeDataServiceUnitTest.cs
> +    //}
Removed ghost code

2024-07-29 09:50 UTC, bseptember approved these changes

2024-07-29 12:49 UTC, EduanO approved these changes

2024-07-29 12:50 UTC, merged