Refactored Employee Service
RetroRabbit/RGO-Server pull request #224
Opened 2024-07-26 10:07 UTC by madwizzard

![Screenshot 2024-07-26 105138](https://github.com/user-attachments/assets/01e58aaf-f678-4599-8b1d-18eec39f2ca0)
![Screenshot 2024-07-26 105150](https://github.com/user-attachments/assets/4762e158-49c2-499c-a664-3d39bb80d904)

The email sending an errorlog test needs to be worked on, but the rest of the lines are covered.

2024-07-26 10:42 UTC, Juanro-Minne approved these changes

2024-07-29 07:16 UTC, EduanO requested changes

2024-07-29 07:16 UTC, EduanO commented on HRIS.Services/Services/EmployeeService.cs
>      public async Task<EmployeeDto?> GetEmployee(string email)
```suggestion
    public async Task<EmployeeDto?> GetEmployeeByEmail(string email)
```

Naming of methods is important to describe them better

2024-07-29 07:51 UTC, EduanO requested changes

2024-07-29 07:51 UTC, EduanO commented on HRIS.Services/Interfaces/IEmployeeService.cs
We do not need `GetEmployeeById` and `GetById` As they do the exact same thing except the one does an include and the otherr does not.

2024-07-29 10:41 UTC, bseptember commented on HRIS.Services/Services/EmployeeService.cs
>      public async Task<EmployeeDto> UpdateEmployee(EmployeeDto employeeDto, string email)
Logic: is string email actually being used in the service, controller and front end or are we using employeeDto.email?

2024-07-29 10:43 UTC, bseptember commented on HRIS.Services/Services/EmployeeService.cs
>      {
Logic: is string email actually being used in the service, controller and front end or are we using employeeDto.email?

2024-07-29 17:05 UTC, EduanO approved these changes

2024-07-30 06:34 UTC, DewanAlberts approved these changes

2024-07-30 06:49 UTC, merged