Dummy seed
RetroRabbit/RGO-Server pull request #232
Opened 2024-08-06 09:43 UTC by KAYEMBAJONATHAN

- Add update the seed dummy

2024-08-06 11:37 UTC, MathildaShongwe15 reviewed
I think you forgot to correct the ID Numbers and the Cellphone Number

2024-08-07 06:48 UTC, bseptember approved these changes

2024-08-07 08:08 UTC, bseptember commented
@KAYEMBAJONATHAN @MathildaShongwe15 @ReitumetseMoloto We are just holding off on this until this ticket is complete:
The reason being the employee table will be updated and the postal table will be removed, therefore the seed data will no longer be valid. Yielding errors.


[Azure board](https://dev.azure.com/retro-rabbit/HRIS/_sprints/taskboard/HRIS%20Team/HRIS/Sprint%2026?workitem=10082)

2024-08-07 08:09 UTC, bseptember requested changes
@KAYEMBAJONATHAN @MathildaShongwe15 @ReitumetseMoloto We are just holding off on this until this 
[ticket](https://dev.azure.com/retro-rabbit/HRIS/_sprints/taskboard/HRIS%20Team/HRIS/Sprint%2026?workitem=10082) is complete:
The reason being the employee table will be updated and the postal table will be removed, therefore the seed data will no longer be valid. Yielding errors.

2024-08-08 13:06 UTC, bseptember requested changes

2024-08-08 13:06 UTC, bseptember commented on RR.UnitOfWork/SEED_DUMMY.sql
> +VALUES (2, '+227716480198', NULL, 'Australia', TIMESTAMPTZ '1996-12-09 22:00:00Z', FALSE, 'na', 'amanders@gmail.com', NULL, NULL, '0231646', 7, TIMESTAMPTZ '2024-03-07 13:10:48.9309Z', 1, NULL, '9902
The work email should all be username@retrorabbit.co.za, instead of amanders@gmail.com, check all the emails.

2024-08-13 10:34 UTC, MathildaShongwe15 approved these changes

2024-08-14 05:54 UTC, bseptember approved these changes

2024-08-14 05:57 UTC, madwizzard approved these changes

2024-08-14 06:01 UTC, merged