Origin/lucien/starter kit endpoint
RetroRabbit/RGO-Server pull request #69
Opened 2024-04-11 11:55 UTC by Lucien-vanWyk

![image](https://github.com/RetroRabbit/RGO-Server/assets/123623749/59daf54b-8879-4004-be6c-365086ef70c5)

![image](https://github.com/RetroRabbit/RGO-Server/assets/123623749/f8afb6db-87da-4371-bed1-a3985176d583)

2024-04-16 08:01 UTC, AWallsRR requested changes

2024-04-19 07:54 UTC, AWallsRR commented
Please resolve all comments

2024-04-19 10:56 UTC, Lucien-vanWyk commented on RR.App.Tests/Controllers/HRIS/EmployeeBankingControllerUnitTests.cs
> +/*
Unit Test I forgot to uncomment, my mistake

2024-04-19 11:00 UTC, Lucien-vanWyk commented on RR.UnitOfWork/Migrations/20240404071150_Setup.Designer.cs
Will do

2024-04-22 06:21 UTC, AWallsRR approved these changes

2024-04-22 06:22 UTC, AWallsRR approved these changes

2024-04-22 06:45 UTC, ReinoRabbit approved these changes

2024-04-22 06:50 UTC, MatthewSchoeman approved these changes

2024-04-22 06:55 UTC, merged